### ISSUE TITLE
SampleConcensusModel fails on lidar points

### ISSUE THREAD

**Issue by pirobot** [robofit/but_velodyne#27]

**Comment by pirobot** [comment]
Thanks for making this package available!  I am trying it out using Gazebo 7 under ROS Kinetic and Ubuntu 16.04.  You can see the simulation setup below:

![image](https://user-images.githubusercontent.com/873507/51149602-a69afb80-1817-11e9-95a2-aab807c582a1.png)

The circles are detected OK by the simulated camera.  See the Hough transform ouput below:

![image](https://user-images.githubusercontent.com/873507/51149641-de09a800-1817-11e9-9afa-732c841fe735.png)

However, the the circles are not detected in the lidar pointcloud by the sphere consensus model.  Instead, I get the following stream of errors:

```
[pcl::SampleConsensusModel::getSamples] Can not select 0 unique points out of 0!
[pcl::RandomSampleConsensus::computeModel] No samples could be selected!
[pcl::SampleConsensusModel::getSamples] Can not select 0 unique points out of 0!
[pcl::RandomSampleConsensus::computeModel] No samples could be selected!
etc
```

I can visualize the pointcloud being processed by Calibration3DMarker.cpp.  Right after the following code:
```
Velodyne::Velodyne scan(pc);
scan.getRings();
scan.intensityByRangeDiff();
```
the pointcloud looks like this:

![image](https://user-images.githubusercontent.com/873507/51149835-aa7b4d80-1818-11e9-8e2e-0b596b42faca.png)

So far so good.  But after the projection onto the camera plane, the pointcloud looks like the following:

```
PointCloud<Velodyne::Point> visible_cloud;
scan.project(P, Rect(0, 0, 672, 376), &visible_cloud);
```
![image](https://user-images.githubusercontent.com/873507/51149942-15c51f80-1819-11e9-87c5-55ddb47c452d.png)

So now we can no longer see the marker at all.

I understand the projection is using the camera_info topic which is shown below.  This matrix is generated by the Gazebo camera plugin:

```
header: 
  seq: 3855
  stamp: 
    secs: 14189
    nsecs: 762000000
  frame_id: "camera_rgb_optical_frame"
height: 376
width: 672
distortion_model: "plumb_bob"
D: [0.0, 0.0, 0.0, 0.0, 0.0]
K: [335.998765805352, 0.0, 336.5, 0.0, 335.998765805352, 188.5, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [335.998765805352, 0.0, 336.5, -0.0, 0.0, 335.998765805352, 188.5, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
```
Can you think of anything that might be going wrong?
